/**
 * Created by mojtaba on 3/14/16.
 */
/*global angular*/
angular
    .module('app')
    .config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('en', {
        'SIGNIN_MSG': 'Sign in with your pushe Account',
        'EMAIL': 'Email',
        'PASSWORD': 'Password',
        'REPASSWORD': 'rePassword',
        'REMEMBER_ME':'Keep me signed in',
        'AS_DEMO':'as demo',
        'SIGNIN':'sign in',
        'FORGOT':'Forgot password?',
        'SIGNUP':'sign up',
        'HAVENT_ACCOUNT':'Do not have an account? ',
        'HAVE_ACCOUNT':'Already have an account? ',
        'FORGOT_PASSWORD':'Forgot your password?',
        'FORGOT_MSG':'Enter your email address below and we will send you instructions on how to change your password.',
        'SIGNUP_MSG':'Sign up to your pushe Account',
        'AGREE':'Agree the ',
        'TERMS':'terms and policy',
        'PROFILE':'Profile',
        'SIGNOUT':'Sign out',
        'HOME':'home',
        'APPLICATIONS':'applications',
        'INSTALLED':'installed',
        'NOTIFICATIONS':'notifications',
        'SECTIONNAME':'admins panel',
        'DEVICE':'device',
        'APPLICATION':'application',
        'INSTALLTIME':'install time',
        'LASTSEEN':'last seen',
        'INSTALL_TIME_PLACE_HOLDER':'1/2/12',
        'LASTSEEN_PLACE_HOLDER':'3/5/13',
        'ADD_NEW_APP':'Add new Application',
        'NAME':'name',
        'PACKNAME':'package name',
        'GLOBAL_SEARCH_PLACEHOLDER':'global search',
        'CANCEL':'cancel',
        'OK':'OK',
        'HELP':'help',
        'SUPPORT':'support',
        'CHANGE_PASS':'change password',
        'ABOUT':'About',
        'RONASH':'Ronash',
        'TEST':'test',
        'NOTIF_TITLE':'title',
        'TEXT':'text',
        'SENDTIME':'send time',
        'STATUS':'status',
        'CONTACT_COUNT':'contact count',
        'CONTACT_RECEIVE':'contact receive',
        'ADD_NOTIFICATION':' اعلان جدید',
        'NOTIF_FIRST_STEP':'define small notification',
        'NEW_NOTIF_TITLE':'make new notification',
        'TITLE_BAR_TEXT':'notification title bar text',
        'ICON_DESC':'change notification icon',
        'SELECT_APP':'select Application',
        'UPLOAD_IMAGE':'Drop images here or click to upload',
        'SELECT_IMAGE':'select image',
        'NO_ACTION':'No Action',
        'OPEN_APPLICATION':'Open Application',
        'OPEN_LINK':'Open URL',
        'CURRENT_PASSWORD':'current password',
        'NEW':'new',
        'PASS_NOT_MATCH':'your password do not match , try again',
        'PASS_CHANGED':'your password changed successfully',
        'CHANGE_PASSWORD_MSG':'change your password',
        'NOTIF_EXTITLE':'complete Title',
        'NOTIF_EXTEXT':'complete Text',
        'NOTIF_BRIEF':'notication brief',
        'NOTIF_IMAGE':'notification image'
    });

    $translateProvider.translations('fa', {
        'SIGNIN_MSG': 'ورود به بخش مدیریت',
        'EMAIL': 'ایمیل',
        'PASSWORD': 'رمز عبور',
        'REPASSWORD': 'تکرار رمز عبور',
        'REMEMBER_ME':'مرا بخاطر بسپار؟',
        'AS_DEMO':'نمایش دمو',
        'SIGNIN':'ورود',
        'FORGOT':'رمز عبور را فراموش کرده اید؟?',
        'SIGNUP':'ثبت نام',
        'HAVENT_ACCOUNT':'ثبت نام نکرده اید؟ ',
        'HAVE_ACCOUNT':'قبلا ثبت نام کرده اید؟ ',
        'FORGOT_PASSWORD':'رمز عبورتان را فراموش کرده اید؟',
        'FORGOT_MSG':'ایمیل خود را وارد نمایید تا نحوه احیا نمودن رمز عبور را برای شما ارسال کنیم.',
        'SIGNUP_MSG':'ثبت نام',
        'AGREE':'Agree the ',
        'TERMS':'terms and policy',
        'PROFILE':'پروفایل',
        'SIGNOUT':'خروج',
        'HOME':'خانه',
        'APPLICATIONS':'اپلیکیشن ها',
        'INSTALLED':'نصب ها',
        'NOTIFICATIONS':'اعلان ها',
        'SECTIONNAME':'مدیریت نوتیفیکیشن',
        'DEVICE':'دستگاه',
        'APPLICATION':'اپلیکیشن',
        'INSTALLTIME':'تاریخ نصب',
        'LASTSEEN':'آخرین بازدید',
        'INSTALL_TIME_PLACE_HOLDER':'۱۳۹۴.۱۱.۲۳',
        'LASTSEEN_PLACE_HOLDER':'۱۳۹۴.۱۲.۳',
        'ADD_NEW_APP':'افزودن اپلیکیشن',
        'NAME':'نام',
        'PACKNAME':'نام بسته اپلیکیشن',
        'GLOBAL_SEARCH_PLACEHOLDER':'جستجو.',
        'CANCEL':'انصراف',
        'OK':'تایید',
        'HELP':'کمک',
        'SUPPORT':'پشتیبانی',
        'CHANGE_PASS':'تغییر رمز عبور',
        'ABOUT':'درباره',
        'RONASH':' روناش ',
        'TEST':' آزمایش ',
        'NOTIF_TITLE':'تیتر',
        'TEXT':'متن',
        'SENDTIME':'زمان ارسال',
        'STATUS':'وضعیت',
        'CONTACT_COUNT':'تعداد نفرات',
        'CONTACT_RECEIVE':'میزان دریافت',
        'ADD_NOTIFICATION':' اعلان جدید',
        'NOTIF_FIRST_STEP':'اعلان کوچک',
        'NEW_NOTIF_TITLE':'ایجاد نوتیفیکیشن جدید',
        'TITLE_BAR_TEXT':'متن نوار اعلان',
        //'ICON_DESC':'در صورتیکه می خواهید آیکون دیگری در اعلان نمایش داده شود، آن را انتخاب کنید.',
        'ICON_DESC':'برای تغییر آیکون در اعلان میبایست عکس را به اینجا بکشید یا اینجا را کلیک کنید',
        'SELECT_APP':'انتخاب اپلیکیشن',
        'UPLOAD_IMAGE':'عکس را به اینجا بکشید یا اینجا را کلیک کنید',
        'SELECT_IMAGE':'انتخاب عکس',
        'ACTION_PLACEHOLDER':'عملکرد کلیک',
        'NO_ACTION':'بدون عملکرد',
        'OPEN_APPLICATION':'باز کردن اپلیکیشن',
        'OPEN_LINK':'باز کردن URL',
        'CURRENT_PASSWORD':'رمز عبور فعلی',
        'NEW':'جدید',
        'PASS_NOT_MATCH':'رمز عبور با تکرار آن مطابق نیست لطفا دوباره امتحان کنید.',
        'PASS_CHANGED':'رمز عبور با موفقیت تغییر کرد',
        'CHANGE_PASSWORD_MSG':'تغییر رمز عبور',
        'NOTIF_EXTITLE':'تیتر کامل',
        'NOTIF_EXTEXT':'متن کامل',
        'NOTIF_BRIEF':'خلاصه',
        'NOTIF_IMAGE':'تصویر اعلان'
    });

    $translateProvider.preferredLanguage('fa');

    $translateProvider.useSanitizeValueStrategy(null);//it do nothing with translate
    //we dont need to sanitize translations also we need to dont sanitize them because we may use below line in translations
        //e.g: '<strong>click kon</strong>'
}]);